yarnPath: .yarn/releases/yarn-2.4.1.cjs
packageExtensions:
  '@semantic-release/commit-analyzer@*':
    dependencies:
      semantic-release: '*'
  cz-lerna-changelog@*:
    dependencies:
      lerna: '*'
  eslint-config-airbnb-base@*:
    dependencies:
      eslint: '*'
      eslint-plugin-import: '*'
  eslint-config-airbnb@*:
    dependencies:
      eslint: '*'
      eslint-plugin-import: '*'
      eslint-plugin-jsx-a11y: '*'
      eslint-plugin-react: '*'
      eslint-plugin-react-hooks: '*'
  '@typescript-eslint/parser@*':
    dependencies:
      eslint: '*'
