packageExtensions:
  '@typescript-eslint/parser@*':
    dependencies:
      eslint: '*'
  eslint-config-airbnb-base@*:
    dependencies:
      eslint: '*'
      eslint-plugin-import: '*'
  eslint-config-airbnb@*:
    dependencies:
      eslint: '*'
      eslint-plugin-import: '*'
      eslint-plugin-jsx-a11y: '*'
      eslint-plugin-react: '*'
      eslint-plugin-react-hooks: '*'

yarnPath: .yarn/releases/yarn-2.4.1.cjs
