name: Main

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [15.x]
        ci_node_index: [0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: typescript-build-cache
        with:
          path: |
            **/dist
          key: typescript-build

      - uses: actions/cache@v2
        id: eslint-cache
        with:
          path: .eslintcache
          key: eslint-cache

      - name: Yarn Install
        run: yarn install --immutable
      - name: Typescript Build
        run: yarn build